version: "3"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: expenses
      POSTGRES_DB: expenses
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
